### ISSUE TITLE
List all NFT for particular account

### ISSUE THREAD

**Issue by JernejHenigman** [near-examples/nft-tutorial#14]
Hi,

I am following https://docs.near.org/docs/tutorials/contracts/nfts/marketplace tutorial and I would like to call function near view $MARKETPLACE_CONTRACT_ID get_supply_by_owner_id '{"account_id": "benji.testnet"}' to list all supply that account_id: "benji.testnet" owns. But I am getting the following error `Unknown argument: benji.testnet}'`

Is this the right function call with its parameters, and should I get in return some sort of list with information? 

What am I doing wrong?

With kind regards
Jernej

**Comment by mattlockyer** [comment]
You need to replace $MARKETPLACE_CONTRACT_ID with the near account id of the contract you want to check. Is $MARKETPLACE_CONTRACT_ID set?

**Comment by JernejHenigman** [comment]
Thank you for quick reply, 

no I have not set $MARKETPLACE_CONTRACT_ID yet, how can I do that and where I find $MARKETPLACE_CONTRACT_ID information? My use case is to list all supply that particular accountId have with near command.

**Comment by mattlockyer** [comment]
It's an environment variable so you can either replace the $MARKETPLACE... with your contract id or you can set the environment variable.


For example:

near view nfts.testnet get_supply_by_owner_id '{"account_id": "benji.testnet"}' 

But I don't know if nfts.testnet is an NFT account... so you replace this with the one you're using in the tutorial.

Hope this helps.

**Comment by JernejHenigman** [comment]
I did exactly that :)). So my command look like this `near view hrust16.testnet get_supply_by_owner_id'{"account_id": "benji.testnet"}'` where hrust16.testnet is account opend for testing purposes but error remains identical, that is` Unknown argument: benji.testnet}'`

What is the issue?

**Comment by mattlockyer** [comment]
there is no contract deployed on the account

https://explorer.testnet.near.org/accounts/hrust16.testnet

**Comment by JernejHenigman** [comment]
I understand, thank you. Can you point me to tutorial or quick guide how to deploy a contract to the account?

With kind regards
Jernej

**Comment by mattlockyer** [comment]
https://www.near-sdk.io/promises/deploy-contract

the example was for using the contract referenced here, which is already deployed:

https://docs.near.org/docs/tutorials/contracts/nfts/predeployed-contract#minting-your-nfts
