### ISSUE TITLE
General question about contracts!

### ISSUE THREAD

**Issue by JernejHenigman** [near-examples/nft-tutorial#15]
Hi NEAR developers, 

I am traversing your guides and I am quite impressed with the work you done.

I have a question regrading contracts.  I started using my actual near account xxxx.near and not xxxx.testnet anymore. 
Will I be able to make near calls with deployed contract from

```
git clone https://github.com/near-examples/nft-tutorial.git 
cd nft-tutorial
git switch 6.royalty
yarn build
```
then I call 
`near deploy --accountId $NFT_CONTRACT_ID --wasmFile out/main.wasm
`
to deploy contract 

then I call

`near call $NFT_CONTRACT_ID new_default_meta '{"owner_id": "'$NFT_CONTRACT_ID'"}' --accountId $NFT_CONTRACT_ID
`

to init contract.

Will I be able to then call a function

`near view $MARKETPLACE_CONTRACT_ID get_supply_sales
`

with contract that I previously deployed?

I do not want to spend to much NEAR on deploying and initializing contracts that does not do its job. I need to pay I think 3 NEAR (2937818518636002900000000  yocto) to deploy.

Thank you for your answers and help

**Comment by BenKurrek** [comment]
Are you talking about deploying a marketplace contract on testnet and then deploying the NFT contract on mainnet and you wanna know if you can interact between the two? Also I would suggest working off the main branch as the other ones are made for the tutorial in docs and are used to show the iterative process of making the contracts.

**Comment by JernejHenigman** [comment]
I am talking about deploying marketplace contract on mainnet and then start using deployed contract on mainnet for trading purposes. I will not be using testnet account at this stage anymore. 

My use case is to buy NFTs with marketplace contract on mainnet. Is that possible?

**Comment by BenKurrek** [comment]
In that case, yes you can definitely deploy these contracts and work with them the same way you have on testnet but on mainnet now. If you have any more questions, don't hesitate to reach out in NEAR's `#dev-support` channel found [here](https://discord.gg/jZmWsvw325).
