### ISSUE TITLE
Some mandatory parameters on `nft_transfer` and `nft_transfer_payout` are not part of NFT standard

### ISSUE THREAD

**Issue by emarai** [near-examples/nft-tutorial#20]
Hi, some new projects are using this example and we have found some parameters are mandatory (which shouldn't from the standard).

The first one is `nft_transfer_payout`, which requires a mandatory `memo`, which is not part of the standard [1]. This is also reflected in the tutorial [2].

https://github.com/near-examples/nft-tutorial/blob/main/nft-contract/src/royalty.rs#L69
```
 fn nft_transfer_payout(
        &mut self,
        receiver_id: AccountId,
        token_id: TokenId,
        approval_id: u64,
        memo: String,
        balance: U128,
        max_len_payout: u32,
 )
 ```
 
 The second one is `nft_transfer` with mandatory `approval_id`, which should be optional from the standard [3].
 
 https://github.com/near-examples/nft-tutorial/blob/main/nft-contract/src/nft_core.rs#L100
 
 ```
     fn nft_transfer(
        &mut self,
        receiver_id: AccountId,
        token_id: TokenId,
        //we introduce an approval ID so that people with that approval ID can transfer the token
        approval_id: u64,
        memo: Option<String>,
    ) {
```
 
 [1] https://nomicon.io/Standards/NonFungibleToken/Payout
 [2] https://docs.near.org/docs/tutorials/contracts/nfts/royalty
 [3] https://nomicon.io/Standards/NonFungibleToken/Core
 
 Edit: made a PR https://github.com/near-examples/nft-tutorial/pull/21

**Comment by andrew-sol** [comment]
+1

I use the wasm file from this repo for local testing and today I found out that `approval_id` is required in the `nft_transfer` method when it shouldn't be.

**Comment by BenKurrek** [comment]
Will take a look later this week thanks for bringing this to my attention.

**Comment by BenKurrek** [comment]
Thanks for the PR - it's been merged. Appreciate it.
