### ISSUE TITLE
yarn build  problem 

### ISSUE THREAD

**Issue by animal81** [near-examples/nft-tutorial#27]
[](url)  });
    const promise = promiseFn.apply(null, args);
    try {
        await promise;
    } catch (e) {

PLEASE help me am new to rust[](url)

**Comment by BenKurrek** [comment]
Hey, I'm not sure what the issue is here. Feel free to ask any rust-related questions in our [rust-support](https://discord.gg/fgHuM8JcKn) channel on discord.
