### ISSUE TITLE
No need to remove return types

### ISSUE THREAD

**Issue by maxzaver** [near-examples/nft-tutorial#30]
The Developer Console tutorial mentions 
> Return types have been removed from this code example so the contract can still compile properly.

With regards to https://github.com/near-examples/nft-tutorial/ . It is however unnecessary to remove return types to make the code compile `todo!()` macro can be used in places of missing code since it coerces to any type.

CC @BenKurrek

**Comment by BenKurrek** [comment]
Thanks - I'll make the changes :)

**Comment by BenKurrek** [comment]
Fixed [here](https://github.com/near/docs/pull/1054)
