### ISSUE TITLE
instructions on tests, tests failing to install deps, near-workspaces etc...

### ISSUE THREAD

**Issue by mattlockyer** [near-examples/nft-tutorial#34]
there's no info on how to run tests

tried to install inside the integration-tests folder, some special version?

![image](https://user-images.githubusercontent.com/321340/180609598-a8b932c0-f536-4cb2-8390-9fdf0a32d80e.png)

**Comment by mattlockyer** [comment]
downgraded to 2.0 workspaces, on ubuntu, AMD, doesn't work

![image](https://user-images.githubusercontent.com/321340/180609873-f2ea988e-ed7d-41d4-87d5-4f82fc8afd98.png)

**Comment by BenKurrek** [comment]
@idea404 do you have any opinions - I can't run any tests due to M1 issues.

**Comment by idea404** [comment]
Hello. workspaces-js v2 is not currently compatible with Rust SDK v4. We're waiting on a release for workspaces-js v2.1.0 that should address this issue. Hence why [the workspaces-js tests are currently commented out in the CI](https://github.com/near-examples/nft-tutorial/blob/99d7386eecddb90f032b8c005a23a67139ab4451/.github/workflows/tests.yml#L29)

**Comment by idea404** [comment]
@mattlockyer what node version are you using? I replicated this error and was able to resolve it by changing node to v16.16.0
