### ISSUE TITLE
Yarn build fails 

### ISSUE THREAD

**Issue by CodeDem** [near-examples/nft-tutorial#37]
I'm trying to follow the minting tutorial from  ```https://docs.near.org/tutorials/nfts/minting```. I followed the guide exactly the same. However, after making all the mentioned changes when I run ```yarn build``` I get following errors.

<img width="985" alt="image" src="https://user-images.githubusercontent.com/8732860/183914521-6caf173e-4ecb-4dd7-8df9-94d4d90d8098.png">

**Comment by Madgeniusblink** [comment]
remove this file https://github.com/near-examples/nft-tutorial/blob/main/rust-toolchain and dont forget to add the wasm32 toolchain: rustup target add wasm32-unknown-unknown.
