### ISSUE TITLE
Version of NFT events is broken

### ISSUE THREAD

**Issue by tifrel** [near-examples/nft-tutorial#48]
The current versioning of NFT events is prefixed by `nft-`:

- https://github.com/near-examples/nft-tutorial/blob/main/nft-contract/src/mint.rs#L60
- https://github.com/near-examples/nft-tutorial/blob/main/nft-contract/src/lib.rs#L28

The [event standards according to the nomicon don't have this prefix](https://nomicon.io/Standards/Tokens/NonFungibleToken/Event) and most of the ecosystem doesn't have that prefix, and it's causing NFTs with that prefix to be ignored by indexers.

**Comment by BenKurrek** [comment]
Thanks for pointing this out - I got mixed up with the spec in the metadata which should be `nft-1.0.0`. I will submit a PR now.
